Calculate bmi test Resolves # 673
AlexSuspect13/Git_traine pull request #674
Opened 2021-07-17 15:08 UTC by askomar

2021-07-17 20:40 UTC, mTeeeur requested changes

2021-07-17 20:40 UTC, mTeeeur commented on calculate_bmi/test/mocha.test.js
> +  it('In result we have Obese string', () => {
IMHO bad names for test cases. I think you should name it according to the jest/mocha best practices
```javascript
it('Should return a normal result', () => {})
it('Should return a undeweight result', () => {})
it('Should return a overweight result', () => {})
```

2021-07-18 07:04 UTC, askomar commented on calculate_bmi/test/mocha.test.js
> +  it('In result we have Obese string', () => {
Ok, thank you) I did not know this)

2021-07-18 07:21 UTC, askomar commented on calculate_bmi/test/mocha.test.js
> +  it('In result we have Obese string', () => {
done

2021-07-18 09:12 UTC, merged